name: marketplace
on: 
  push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Node ${{ matrix.node }} sample
        uses: actions/setup-node@v4
        with:
          node-version: 14
      - name: verification of node version
        run: node --version
